apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace.name }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.app.profile | quote }}
  SERVER_PORT: {{ .Values.app.port | quote }}
  MYSQL_URL: "jdbc:mysql://{{ .Values.mysql.service }}:3306/{{ .Values.mysql.database }}"