apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.app.name }}

spec:
  replicas: {{ .Values.app.replicas }}

  selector:
    matchLabels:
      app: {{ .Values.app.name }}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}

    spec:

      tolerations:
        - key: {{ .Values.app.toleration.key | quote }}
          operator: Equal
          value: {{ .Values.app.toleration.value | quote }}
          effect: NoSchedule

      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - {{ .Values.app.affinity.nodeRole }}

      initContainers:
        - name: wait-for-mysql
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z {{ .Values.mysql.service }} {{ .Values.mysql.port }}; do
                echo "Waiting for MySQL...";
                sleep 3;
              done
              echo "MySQL is ready!"

      containers:
        - name: {{ .Values.app.name }}

          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"

          imagePullPolicy: {{ .Values.app.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.app.port }}

          envFrom:
            - configMapRef:
                name: {{ .Values.configMap.name }}

          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: MYSQL_USER

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: MYSQL_PASSWORD

          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.app.port }}
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.app.port }}
            initialDelaySeconds: 45
            periodSeconds: 10
            failureThreshold: 3