# StorageClass only
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{.Values.storageclass.name}}
provisioner: ebs.csi.aws.com
parameters:
  type: {{ .Values.storageClass.type }}
  fsType: ext4
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
# PVC only
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.pvcName }}
  namespace: {{ .Values.namespace.name }}
spec:
  storageClassName: {{ .Values.storageClass.name }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}