apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace.name }}
type: Opaque
data:
  MYSQL_USER: {{ .Values.mysql.username | b64enc }}
  MYSQL_PASSWORD: {{ .Values.mysql.password | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword | b64enc }}