apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.service.name }}
  namespace: {{ .Values.namespace.name }}
  annotations:
    alb.ingress.kubernetes.io/target-type: ip

spec:
  selector:
    app: {{ .Values.app.name }}

  ports:
    - name: http
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.port }}
      protocol: TCP

  type: {{ .Values.app.service.type }}