namespace:
  name: petclinic

labels:
  app: petclinic
  env: staging

secret:
  name: petclinic-secret

configMap:
  name: petclinic-config

app:
  profile: mysql
  port: 8080

mysql:
  service: mysql-service
  database: petclinic
  username: petclinic
  password: petclinic
  rootPassword: root

storageClass:
  name: ebs-gp3
  type: gp3
  reclaimPolicy: Retain

persistence:
  pvcName: mysql-pvc
  accessMode: ReadWriteOnce
  size: 5Gi

mysql:
  name: mysql
  replicas: 1

  image: mysql:8.0

  service: mysql-service
  port: 3306

  database: petclinic

  username: petclinic
  password: petclinic
  rootPassword: root

  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

app:
  name: petclinic

  replicas: 2

  image:
    repository: 316777658873.dkr.ecr.us-east-1.amazonaws.com/petclinic
    tag: latest
    pullPolicy: Always

  service:
    name: petclinic-service
    type: ClusterIP
    port: 80

  port: 8080

  profile: mysql

  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

  toleration:
    key: app
    value: petclinic

  affinity:
    nodeRole: app

ingress:
  name: petclinic-ingress

  host: petclinic.kkdev.in

  className: alb

  scheme: internet-facing

  certificateArn: arn:aws:acm:us-east-1:316777658873:certificate/1555ccb6-9735-4a8a-bf51-ec9276843b36

  loadBalancerName: petclinic-alb

  healthCheckPath: /actuator/health

  tags: env=staging,app=petclinic


autoscaling:
  enabled: true

  name: petclinic-hpa

  minReplicas: 2
  maxReplicas: 6

  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 70